---
title: "Zomato Banglore Plots"
author: "19BCE1753-Daksh"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Libraries
```{r, echo=FALSE}
library(dplyr)
library(recommenderlab)
library(data.table)
library(reshape2)
library(ggplot2)
library(RColorBrewer)
```


## Loading the Dataset
```{r}
df <- read.csv("zomato_pre-processed.csv")
#head(df)
```


```{r}
summary(df)
str(df)
```

# Visualising the Dataset

### Plot to decribe Online Ordering Facility
```{r}
online_order = df$online_order
barplot(table(online_order),
      main = "Restaurants With Online Ordering Facility",
      ylab = "Count",
      col=brewer.pal(n = 3, name = "Pastel1"))
table(online_order)
```

```{r}
rate = df$rate
h <- hist(rate,
          main="Restaurants Ratings",
          xlab="Rating from 1.0 to 5.0",
          breaks=30)
text(h$mids,h$counts,labels=h$counts, adj=c(0.5, -0.5))

print('Mean Rating')
print(mean(rate))

# h <- hist(rate, main="Restaurants Ratings", xlab="Rating from 1.0 to 5.0",col=brewer.pal(n = 30, name = "Set3"), breaks=30)
```

### Plot to describe Restaurant Table Booking Option
```{r}
book_table = df$book_table
barplot(table(book_table),
      main = "Restaurants With Table Booking Option",
      ylab = "Count",
      col=brewer.pal(n = 3, name = "Pastel2"))
table(book_table)
```

### In Bangalore city,in which area has maximum number of restaurants
```{r}
location = df$location
barplot(table(location))
setNames(data.frame(table(location)), c("Location", "Number of restaurants"))
```

### 'Rate' vs 'Restaurant type' graph
```{r}
#plot(df$rate, df$rest_type)

# ggplot(df, aes(x = rate, y = rest_type)) +  geom_line()

ggplot(df, aes(y = rate, x = rest_type)) + geom_line()

#Dont paste this
```


